# ============================================
# ????????? ????????? CONFIG SERVER
# ============================================
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false
spring.cloud.compatibility-verifier.enabled=false

# ============================================
# ??? ???????
# ============================================
spring.application.name=user-service

# ============================================
# ????????? ?????
# ============================================
server.port=0

# ============================================
# ???? ?????? (????????)
# ============================================
spring.datasource.url=jdbc:postgresql://postgres:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=1qaz!QAZ
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ============================================
# KAFKA (????????)
# ============================================
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=userEvent:io.github.zaur2025.userservicespringkafka.kafka.UserEvent

app.kafka.topic.user-events=user-events-topic

# ============================================
# EUREKA
# ============================================
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.uuid}

# ============================================
# CIRCUIT BREAKER
# ============================================
resilience4j.circuitbreaker.instances.kafkaProducer.sliding-window-size=10
resilience4j.circuitbreaker.instances.kafkaProducer.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.kafkaProducer.wait-duration-in-open-state=10000
resilience4j.circuitbreaker.instances.kafkaProducer.permitted-number-of-calls-in-half-open-state=3

# ============================================
# ACTUATOR
# ============================================
management.endpoints.web.exposure.include=health,info,circuitbreakers
management.health.circuitbreakers.enabled=true

# ============================================
# ???????????
# ============================================
logging.level.io.github.zaur2025.userservicespringkafka=DEBUG