spring.application.name=discovery-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.security.user.name=eureka
spring.security.user.password=${EUREKA_PASSWORD:eureka-password}

logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG

spring.cloud.compatibility-verifier.enabled=false